### 1. Initial Data Preparation

#### Importing libraries

In [1]:
import pandas as pd

frame = pd.read_csv('Merged_Flight_Weather.csv')

#### Converting datatypes of columns, dropping unnececessary columns

In [2]:
frame = frame.drop(columns=[ 'time', 'date', 'FlightDate', 'DepTime','ArrDelayMinutes', 
                      'ArrTime'])

frame.drop_duplicates(inplace=True)

frame["Origin"] = frame["Origin"].astype('category')
frame["Dest"] = frame["Dest"].astype('category')


frame["Origin"] = frame["Origin"].cat.codes

frame["Dest"] = frame["Dest"].cat.codes

In [3]:
frame.drop(frame.columns[0], axis=1, inplace=True)
frame.shape

(20197718, 28)

In [4]:
frame.dropna(axis=0)

frame['weatherCode'] = frame['weatherCode'].astype(int)

frame['visibility'] = frame['visibility'].astype(int)
frame['pressure'] = frame['pressure'].astype(int)
frame['cloudcover'] = frame['cloudcover'].astype(int)
frame['DewPointF'] = frame['DewPointF'].astype(int)
frame['WindGustKmph'] = frame['WindGustKmph'].astype(int)
frame['tempF'] = frame['tempF'].astype(int)
frame['WindChillF'] = frame['WindChillF'].astype(int)
frame['tempF'] = frame['tempF'].astype(int)

frame['CRSArrTime'] = frame['CRSArrTime'].astype(int)
frame['CRSDepTime'] = frame['CRSDepTime'].astype(int)
frame['DayofMonth'] = frame['DayofMonth'].astype(int)

frame['DestAirportID'] = frame['DestAirportID'].astype(int)
frame['Month'] = frame['Month'].astype(int)
frame['Quarter'] = frame['Quarter'].astype(int)
frame['Year'] = frame['Year'].astype(int)
frame['OriginAirportID'] = frame['OriginAirportID'].astype(int)

frame.dtypes



index_x              int64
ArrDel15           float64
CRSArrTime           int64
CRSDepTime           int64
DayofMonth           int64
DepDel15           float64
DepDelayMinutes    float64
Dest                  int8
DestAirportID        int64
Month                int64
Origin                int8
OriginAirportID      int64
Quarter              int64
Year                 int64
DeptTime             int64
index_y              int64
windspeedKmph        int64
winddirDegree        int64
weatherCode          int64
precipMM           float64
visibility           int64
pressure             int64
cloudcover           int64
DewPointF            int64
WindGustKmph         int64
tempF                int64
WindChillF           int64
humidity             int64
dtype: object

In [5]:
frame["Origin"] = frame["Origin"].astype('category')
frame["Dest"] = frame["Dest"].astype('category')

In [6]:
frame.dtypes
frame.shape

(20197718, 28)

In [7]:
frame = frame.drop(columns=['index_x', 'index_y'])

In [8]:
import pandas as pd
import numpy as np

def clean_dataset(df):
    assert isinstance(df, pd.DataFrame)
    df.dropna(inplace=True)
    indices_to_keep = ~df.isin([np.nan, np.inf, -np.inf]).any(1)
    return df[indices_to_keep].astype(np.float64)
clean_dataset(frame)

ArrDel15  CRSArrTime  CRSDepTime  DayofMonth  DepDel15  \
0              0.0      1602.0       745.0         1.0       0.0   
1              0.0      1602.0       745.0         1.0       0.0   
2              0.0      1602.0       745.0         1.0       0.0   
3              0.0      1602.0       745.0         1.0       0.0   
4              0.0      1602.0       745.0         1.0       0.0   
...            ...         ...         ...         ...       ...   
20197713       1.0       428.0       130.0        14.0       1.0   
20197714       1.0       428.0       130.0        14.0       1.0   
20197715       1.0       428.0       130.0        14.0       1.0   
20197716       1.0       428.0       130.0        14.0       1.0   
20197717       1.0       428.0       130.0        14.0       1.0   

          DepDelayMinutes  Dest  DestAirportID  Month  Origin  ...  \
0                     0.0   6.0        12478.0    1.0    13.0  ...   
1                     0.0   6.0        12478.0    1.0    13.0  ...   
2                     0.0   6.0        12478.0    1.0    13.0  ...   
3                     0.0   6.0        12478.0    1.0    13.0  ...   
4                     0.0   6.0        12478.0    1.0    13.0  ...   
...                   ...   ...            ...    ...     ...  ...   
20197713             48.0   2.0        11292.0   12.0     7.0  ...   
20197714             48.0   2.0        11292.0   12.0     7.0  ...   
20197715             48.0   2.0        11292.0   12.0     7.0  ...   
20197716             48.0   2.0        11292.0   12.0     7.0  ...   
20197717             48.0   2.0        11292.0   12.0     7.0  ...   

          weatherCode  precipMM  visibility  pressure  cloudcover  DewPointF  \
0               296.0       1.4         9.0    1029.0       100.0       42.0   
1               113.0       0.0        10.0    1045.0         0.0       -2.0   
2               113.0       0.0        10.0    1020.0         1.0       30.0   
3               122.0       0.0        10.0    1025.0       100.0       38.0   
4               143.0       0.0         4.0    1023.0        93.0       43.0   
...               ...       ...         ...       ...         ...        ...   
20197713        122.0       0.0         6.0    1011.0        70.0       17.0   
20197714        116.0       0.0        10.0    1029.0        28.0       35.0   
20197715        113.0       0.0        10.0    1018.0         0.0        6.0   
20197716        113.0       0.0        10.0    1018.0         0.0       36.0   
20197717        113.0       0.0        10.0    1018.0         0.0       50.0   

          WindGustKmph  tempF  WindChillF  humidity  
0                 27.0   47.0        41.0      84.0  
1                 21.0    3.0        -9.0      80.0  
2                 15.0   51.0        47.0      46.0  
3                 23.0   42.0        34.0      92.0  
4                 12.0   46.0        43.0      92.0  
...                ...    ...         ...       ...  
20197713          26.0   22.0         9.0      82.0  
20197714          10.0   40.0        37.0      81.0  
20197715          30.0   45.0        40.0      20.0  
20197716          18.0   49.0        48.0      60.0  
20197717           9.0   59.0        59.0      73.0  

[20197718 rows x 26 columns]

### 2. Target to be predicted is if a flight is delayed or not based on the weather. Features from weather and flight data are considered for prediction

#### Splitting into training and testing sets

In [9]:
y = frame['ArrDel15']
X = frame.drop(columns = ['ArrDel15'])

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.7)

### 3. Decision Tree Classifier

In [10]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 0, splitter = 'best', max_depth = 2)
classifier.fit(X_train, y_train)

DecisionTreeClassifier(criterion='entropy', max_depth=2, random_state=0)

#### Computing values for Decision tree

In [11]:
y_pred = classifier.predict(X_test)


#### Computing metrics for Decision tree

In [12]:
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
print("accuracy: ",accuracy_score(y_test, y_pred))
print("precision: ",precision_score(y_test, y_pred))
print("Recall: ", recall_score(y_test, y_pred))
print("f1_score:", f1_score(y_test, y_pred))



[[4667479  109952]
 [ 404352  877533]]
accuracy:  0.9151217728205626
precision:  0.8886545112077652
Recall:  0.6845645280192841
f1_score: 0.773371464327104


### 4. Training the Support vector Classifier on Training Model

In [13]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
gnb.fit(X_train, y_train)
  

GaussianNB()

#### Computing values for test set for SVC

In [14]:
y_pred = gnb.predict(X_test)

#### Computing metrics for SVC

In [15]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[4517561  259870]
 [ 315764  966121]]


0.905000168335832

### 5. Results - Accuracy for SVC is 91% which is almost same as the accuracy of Naive Bayes Classifier that is 90%. 

### 6. Final Evaluation with test set

In [16]:
y_prediction=classifier.predict(X_test)

In [17]:
print(y_prediction)

[0. 0. 0. ... 0. 0. 0.]


In [19]:
y_pred_svc=gnb.predict(X_test)

In [20]:
print(y_pred_svc)

[0. 0. 1. ... 0. 0. 0.]


### 7. Parameters found and things learnt

random_state, splitter, max_depth are the parameters used in decision tree classifier. I used best for splitter and max depth as 2, If I increase max depth then it leads to overfitting.

From this project milestone, I have learnt that- If there are n features and a target variable which is a categorical one,
then using the classifier algorithms, a model can be generated by giving the labelled training data to the model.
The model learns the patterns that are present in the training data and this patterns can be used to predict the values of the testing data.